menu:
  博客文章: /
  归档: /archives

widgets: 
- search
- category
- recent_posts
- tag
- tagcloud
- weibo

excerpt_link: 阅读全文

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: false
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

jiathis:
  enable: true

fancybox: true

google_analytics:
rss: /atom.xml